### ISSUE TITLE
error in creating new reviews

### ISSUE THREAD

**Issue by mrsminiberger** [wliu-levansoft/media-coding#29] opened 2014-05-30 13:31 UTC
Sys.WebForms.PageRequestManagerServerErrorException: An unknown error occurred while processing the request on the server. The status code returned from the server was: 500

And then the review that I created doesn't show up...

**Comment by dannyl07** [comment] 2014-05-30 14:32
Could you try it one more time, there was an issue trapping errors and logging it to the file system.  I fixed that problem. . .but would you be able to reproduce it error so I can see what the root cause is?  Thanks.

**Comment by mrsminiberger** [comment] 2014-05-31 00:53
just tried it on review 20120328-011146. Same error.

**Comment by dannyl07** [comment] 2014-05-31 02:57
Looks like the error was caused by too many datasets shown on the single page when you search for "*" as media name.  For now I raised the limit for how many datasets can be shown on a single page.  But I think in order to keep the web application scalable, we should think about a better way to display the full list of medias.  I'm thinking perhaps allow the results to be shown in pages...  Such as 50 items per page.  We can work on that in the future.  Do you mind trying it again and see if this issue is resolved before I close this issue.  Thanks.

**Comment by dannyl07** [comment] 2014-06-05 17:57
Is this issue resolved with the last fix?

**Comment by mrsminiberger** [comment] 2014-06-06 14:17
yes- resolved with the last fix. Thanks!

**Closed as completed** 2014-06-06 14:19 UTC
